import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    background: "#FFFFFF",
    backgroundAlt: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    surfaceSoft: "#FFFFFF",
    surfaceMuted: "#FFFFFF",
    surfaceStrong: "#1F1B15",
    border: "#F0DDCA",
    divider: "#EFE3D5",
    borderStrong: "#E5C6A8",
    primary: "#FF7A1A",
    primaryDeep: "#F2630D",
    primarySoft: "#FFF0E2",
    textPrimary: "#15130F",
    textSecondary: "#51473F",
    textMuted: "#8B8176",
    textInverse: "#FFF5E8",
    success: "#18A058",
    successSoft: "#EAF8EF",
    warning: "#B86A13",
    warningSoft: "#FFF3D8",
    danger: "#F04438",
    dangerSoft: "#FFF0EF",
    blueSoft: "#EDF6FF",
    blueBorder: "#CBE2FF",
    blueText: "#2173D8",
    purpleSoft: "#F2EDFF",
    purpleText: "#7C5CE3",
    greenSoft: "#EAF8EF",
    greenText: "#18A058",
    orangeGradientStart: "#FFF1D8",
    orangeGradientEnd: "#FFE1B8",
    backButtonBackground: "#FFFFFF",
    backButtonBorder: "#F0DDCA",
    backButtonText: "#15130F",
    shadow: "rgba(117, 77, 31, 0.12)",
    shadowSoft: "rgba(117, 77, 31, 0.08)",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 64,
    container: 18,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 20,
    xl: 26,
    pill: 999,
  },
  typography: {
    eyebrow: 12,
    label: 14,
    body: 16,
    section: 20,
    title: 32,
    display: 46,
    hero: 40,
  },
  touch: {
    minHeight: 52,
  },
} as const;

export const sharedStyles = StyleSheet.create({
  screenStack: {
    gap: theme.spacing.md,
  },
  pageHeader: {
    gap: theme.spacing.sm,
    paddingBottom: theme.spacing.xs,
  },
  pageHeaderCentered: {
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  eyebrow: {
    color: theme.colors.primaryDeep,
    fontSize: theme.typography.eyebrow,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  pageTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.title,
    fontWeight: "800",
    letterSpacing: -0.8,
    lineHeight: 36,
  },
  displayValue: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.display,
    fontWeight: "300",
    letterSpacing: -1,
    lineHeight: 52,
  },
  pageCopy: {
    color: theme.colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.section,
    fontWeight: "700",
    letterSpacing: -0.4,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.xl,
    borderWidth: 1,
    padding: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 3,
  },
  cardSoft: {
    backgroundColor: theme.colors.surfaceSoft,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.xl,
    borderWidth: 1,
    padding: theme.spacing.md,
  },
  input: {
    backgroundColor: theme.colors.surfaceElevated,
    borderBottomColor: theme.colors.primary,
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    color: theme.colors.textPrimary,
    fontSize: theme.typography.body,
    minHeight: 46,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 12,
  },
  textArea: {
    minHeight: 100,
    paddingTop: 12,
    textAlignVertical: "top",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.md,
    justifyContent: "center",
    minHeight: 46,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: theme.typography.body,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.primary,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 46,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: theme.colors.primaryDeep,
    fontSize: theme.typography.body,
    fontWeight: "700",
  },
  chip: {
    alignItems: "center",
    backgroundColor: theme.colors.primarySoft,
    borderColor: "transparent",
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  chipActiveLight: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
  },
  chipActiveDark: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  chipText: {
    color: theme.colors.primaryDeep,
    fontSize: theme.typography.label,
    fontWeight: "600",
  },
  chipTextInverse: {
    color: "#FFFFFF",
  },
  helperBox: {
    backgroundColor: theme.colors.surfaceSoft,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    padding: 14,
  },
  helperTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.label,
    fontWeight: "700",
    marginBottom: theme.spacing.xs,
  },
  helperText: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  lineList: {
    borderTopColor: theme.colors.divider,
    borderTopWidth: 1,
  },
  lineRow: {
    borderBottomColor: theme.colors.divider,
    borderBottomWidth: 1,
    paddingVertical: 12,
  },
  lineRowTitle: {
    color: theme.colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  lineRowSubtitle: {
    color: theme.colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 3,
  },
  lineRowValue: {
    color: theme.colors.textPrimary,
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
  },
  compactSummaryRow: {
    alignItems: "center",
    borderBottomColor: theme.colors.divider,
    borderBottomWidth: 1,
    borderTopColor: theme.colors.divider,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  emptyText: {
    color: theme.colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  successText: {
    color: theme.colors.success,
    fontSize: 14,
    lineHeight: 22,
  },
  warningText: {
    color: theme.colors.warning,
    fontSize: 14,
    lineHeight: 22,
  },
});
