import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    appBackground: "#eef1e8",
    headerBackground: "#f3f5ed",
    surface: "#fbfaf4",
    surfaceMuted: "#f3f6ec",
    surfaceStrong: "#17251b",
    inputBackground: "#fffef8",
    border: "#d5dcc7",
    borderStrong: "#c7d0ba",
    textPrimary: "#18201a",
    textSecondary: "#50604d",
    textMuted: "#65715f",
    textInverse: "#f8f4e7",
    accent: "#d7f171",
    accentSoft: "#eef6be",
    success: "#2d6b3f",
    successSoft: "#ebf5ee",
    warning: "#8a5a22",
    warningSoft: "#fff3de",
    danger: "#9b2f20",
    dangerSoft: "#f8e5df",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  radius: {
    sm: 10,
    md: 12,
    lg: 16,
    pill: 999,
  },
  typography: {
    eyebrow: 12,
    body: 14,
    label: 13,
    section: 18,
    title: 28,
    hero: 32,
  },
  touch: {
    minHeight: 48,
  },
} as const;

export const sharedStyles = StyleSheet.create({
  pageHeader: {
    gap: theme.spacing.xs,
  },
  eyebrow: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.eyebrow,
    fontWeight: "700",
  },
  pageTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.title,
    fontWeight: "800",
    lineHeight: 34,
  },
  pageCopy: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.body,
    lineHeight: 22,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.section,
    fontWeight: "800",
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    padding: theme.spacing.lg,
  },
  input: {
    backgroundColor: theme.colors.inputBackground,
    borderColor: theme.colors.borderStrong,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    color: theme.colors.textPrimary,
    fontSize: theme.typography.body,
    minHeight: theme.touch.minHeight,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
  },
  textArea: {
    minHeight: 96,
    paddingTop: theme.spacing.md,
    textAlignVertical: "top",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceStrong,
    borderRadius: theme.radius.md,
    justifyContent: "center",
    minHeight: theme.touch.minHeight,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  primaryButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.typography.body,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: theme.touch.minHeight,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  secondaryButtonText: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.body,
    fontWeight: "700",
  },
  chip: {
    backgroundColor: theme.colors.inputBackground,
    borderColor: theme.colors.borderStrong,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    minHeight: 40,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 9,
  },
  chipActiveLight: {
    backgroundColor: theme.colors.accentSoft,
    borderColor: theme.colors.accent,
  },
  chipActiveDark: {
    backgroundColor: theme.colors.surfaceStrong,
    borderColor: theme.colors.surfaceStrong,
  },
  chipText: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.label,
    fontWeight: "700",
  },
  chipTextInverse: {
    color: theme.colors.textInverse,
  },
  helperBox: {
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
  },
  helperTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.label,
    fontWeight: "700",
    marginBottom: theme.spacing.xs,
  },
  helperText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.body,
    lineHeight: 21,
  },
  emptyText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.body,
    lineHeight: 21,
  },
  successText: {
    color: theme.colors.success,
    fontSize: theme.typography.label,
    lineHeight: 20,
  },
  warningText: {
    color: theme.colors.warning,
    fontSize: theme.typography.label,
    lineHeight: 20,
  },
});
