import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    background: "#FCF8FF",
    backgroundAlt: "#F7F3FC",
    surface: "#FFFFFF",
    surfaceSoft: "#F6F2FD",
    surfaceMuted: "#F1ECF7",
    surfaceStrong: "#312F38",
    border: "#E5E1EC",
    borderStrong: "#C8C4D6",
    primary: "#8A7CFB",
    primaryDeep: "#5A4AC7",
    primarySoft: "#F3F1FF",
    textPrimary: "#1C1B22",
    textSecondary: "#474553",
    textMuted: "#787585",
    textInverse: "#F3EFFA",
    success: "#4A7B5A",
    successSoft: "#EEF7F0",
    warning: "#8D640B",
    warningSoft: "#FFF6E6",
    danger: "#B54A4A",
    dangerSoft: "#FCECEC",
    shadow: "rgba(39, 28, 77, 0.08)",
    shadowSoft: "rgba(39, 28, 77, 0.04)",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 40,
    xxl: 64,
    container: 20,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 999,
  },
  typography: {
    eyebrow: 12,
    label: 14,
    body: 16,
    section: 22,
    title: 34,
    display: 44,
    hero: 40,
  },
  touch: {
    minHeight: 48,
  },
} as const;

export const sharedStyles = StyleSheet.create({
  screenStack: {
    gap: theme.spacing.lg,
  },
  pageHeader: {
    gap: theme.spacing.sm,
  },
  pageHeaderCentered: {
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  eyebrow: {
    color: theme.colors.primaryDeep,
    fontSize: theme.typography.eyebrow,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  pageTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.title,
    fontWeight: "800",
    letterSpacing: -0.8,
    lineHeight: 40,
  },
  displayValue: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.display,
    fontWeight: "300",
    letterSpacing: -1,
    lineHeight: 52,
  },
  pageCopy: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.body,
    lineHeight: 24,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.section,
    fontWeight: "700",
    letterSpacing: -0.4,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    padding: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 2,
  },
  cardSoft: {
    backgroundColor: theme.colors.surfaceSoft,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    padding: theme.spacing.md,
  },
  input: {
    backgroundColor: theme.colors.surface,
    borderBottomColor: theme.colors.primary,
    borderBottomWidth: 1.5,
    borderColor: theme.colors.borderStrong,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    color: theme.colors.textPrimary,
    fontSize: theme.typography.body,
    minHeight: theme.touch.minHeight,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 14,
  },
  textArea: {
    minHeight: 104,
    paddingTop: 14,
    textAlignVertical: "top",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.md,
    justifyContent: "center",
    minHeight: theme.touch.minHeight,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: theme.typography.body,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.primary,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: theme.touch.minHeight,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: theme.colors.primaryDeep,
    fontSize: theme.typography.body,
    fontWeight: "700",
  },
  chip: {
    alignItems: "center",
    backgroundColor: theme.colors.primarySoft,
    borderColor: "transparent",
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  chipActiveLight: {
    backgroundColor: "#E9E3FF",
    borderColor: theme.colors.primary,
  },
  chipActiveDark: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  chipText: {
    color: theme.colors.primaryDeep,
    fontSize: theme.typography.label,
    fontWeight: "600",
  },
  chipTextInverse: {
    color: "#FFFFFF",
  },
  helperBox: {
    backgroundColor: theme.colors.surfaceSoft,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    padding: theme.spacing.md,
  },
  helperTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.label,
    fontWeight: "700",
    marginBottom: theme.spacing.xs,
  },
  helperText: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  emptyText: {
    color: theme.colors.textMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  successText: {
    color: theme.colors.success,
    fontSize: 14,
    lineHeight: 22,
  },
  warningText: {
    color: theme.colors.warning,
    fontSize: 14,
    lineHeight: 22,
  },
});
