import type {
  Account,
  AppSettings,
  Asset,
  JournalEntry,
  Liability,
  ReportPeriod,
  Transaction,
} from "../domain/models";
import { generateHistoricalTransactions } from "./historicalDemoData";

export const APP_VERSION = "0.1.0";

const now = "2026-04-30T00:00:00.000Z";

export interface AppData {
  version: string;
  accounts: Account[];
  transactions: Transaction[];
  assets: Asset[];
  liabilities: Liability[];
  journalEntries: JournalEntry[];
  settings: AppSettings;
  currentPeriod: ReportPeriod;
}

const accounts: Account[] = [
  {
    id: "account-cash-wallet",
    name: "现金钱包",
    type: "cash",
    balance: 20000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "日常备用",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-cmb-bank",
    name: "招商银行活期",
    type: "bank",
    balance: 180000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "工资卡",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-icbc-bank",
    name: "工商银行活期",
    type: "bank",
    balance: 75000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "生活卡",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-alipay",
    name: "支付宝余额",
    type: "alipay",
    balance: 12000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "线上消费",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-wechat",
    name: "微信零钱",
    type: "wechat",
    balance: 8000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "小额支付",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-eastmoney",
    name: "东方财富证券",
    type: "securities",
    balance: 520000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "A股账户",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-futu",
    name: "富途证券",
    type: "securities",
    balance: 380000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "港美股账户",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-htsc-etf",
    name: "华泰证券 ETF 账户",
    type: "securities",
    balance: 630000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "ETF账户",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-ttfund",
    name: "天天基金账户",
    type: "fund",
    balance: 320000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "公募基金",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-yuebao",
    name: "余额宝",
    type: "fund",
    balance: 120000,
    currency: "CNY",
    isEnabled: true,
    isActive: true,
    note: "货币基金",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-cmb-credit-card",
    name: "招商信用卡",
    type: "creditCard",
    balance: 0,
    currency: "CNY",
    currentDebt: 38000,
    creditLimit: 200000,
    billDay: 10,
    repaymentDay: 25,
    isEnabled: true,
    isActive: true,
    note: "日常刷卡",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-margin",
    name: "融资融券账户",
    type: "securities",
    balance: 0,
    currency: "CNY",
    currentDebt: 150000,
    isEnabled: true,
    isActive: true,
    note: "杠杆账户",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "account-ccb-old",
    name: "建设银行卡",
    type: "bank",
    balance: 0,
    currency: "CNY",
    isEnabled: false,
    isActive: false,
    note: "旧卡",
    createdAt: now,
    updatedAt: now,
  },
];

const assets: Asset[] = [
  {
    id: "asset-cash-wallet",
    name: "现金钱包",
    category: "现金",
    amount: 20000,
    valuationMethod: "currentValue",
    currentValue: 20000,
    accountId: "account-cash-wallet",
    note: "日常备用",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-cmb-bank",
    name: "招商银行活期",
    category: "银行卡",
    amount: 180000,
    valuationMethod: "currentValue",
    currentValue: 180000,
    accountId: "account-cmb-bank",
    note: "工资卡",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-icbc-bank",
    name: "工商银行活期",
    category: "银行卡",
    amount: 75000,
    valuationMethod: "currentValue",
    currentValue: 75000,
    accountId: "account-icbc-bank",
    note: "生活卡",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-alipay",
    name: "支付宝余额",
    category: "支付账户",
    amount: 12000,
    valuationMethod: "currentValue",
    currentValue: 12000,
    accountId: "account-alipay",
    note: "线上消费",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-wechat",
    name: "微信零钱",
    category: "支付账户",
    amount: 8000,
    valuationMethod: "currentValue",
    currentValue: 8000,
    accountId: "account-wechat",
    note: "小额支付",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-yuebao",
    name: "余额宝 / 货币基金",
    category: "货币基金",
    amount: 120000,
    valuationMethod: "currentValue",
    currentValue: 120000,
    accountId: "account-yuebao",
    note: "短期流动资金",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-large-cd-a",
    name: "大额存单 A",
    category: "大额存单",
    amount: 300000,
    valuationMethod: "manual",
    currentValue: 300000,
    note: "稳定收益",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-short-bond",
    name: "国债逆回购 / 短债",
    category: "短债工具",
    amount: 160000,
    valuationMethod: "manual",
    currentValue: 160000,
    note: "低波动现金管理",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-bond-fund",
    name: "债券基金",
    category: "债券基金",
    amount: 220000,
    valuationMethod: "manual",
    currentValue: 220000,
    note: "中低风险配置",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-a-share",
    name: "A股股票账户",
    category: "A股股票",
    amount: 520000,
    valuationMethod: "manual",
    currentValue: 520000,
    accountId: "account-eastmoney",
    note: "主动投资",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-hk-us-stock",
    name: "港美股账户",
    category: "港美股",
    amount: 380000,
    valuationMethod: "manual",
    currentValue: 380000,
    accountId: "account-futu",
    note: "海外权益资产",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-broad-etf",
    name: "宽基 ETF",
    category: "宽基ETF",
    amount: 450000,
    valuationMethod: "manual",
    currentValue: 450000,
    accountId: "account-htsc-etf",
    note: "指数配置",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-sector-etf",
    name: "行业 ETF",
    category: "行业ETF",
    amount: 180000,
    valuationMethod: "manual",
    currentValue: 180000,
    accountId: "account-htsc-etf",
    note: "行业增强",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-mutual-fund",
    name: "公募混合基金",
    category: "公募基金",
    amount: 320000,
    valuationMethod: "manual",
    currentValue: 320000,
    accountId: "account-ttfund",
    note: "长期配置",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-gold",
    name: "黄金 ETF / 实物金",
    category: "黄金",
    amount: 160000,
    valuationMethod: "manual",
    currentValue: 160000,
    accountId: "account-eastmoney",
    note: "避险配置",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-fx",
    name: "美元存款 / 外币",
    category: "外币资产",
    amount: 130000,
    valuationMethod: "manual",
    currentValue: 130000,
    note: "外币储备",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-home",
    name: "自住房估值",
    category: "房产",
    amount: 1250000,
    valuationMethod: "manual",
    purchaseDate: "2023-08-18",
    currentValue: 1250000,
    note: "自住房",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-car",
    name: "车辆估值",
    category: "车辆",
    amount: 160000,
    valuationMethod: "manual",
    purchaseDate: "2025-05-20",
    currentValue: 160000,
    note: "家用车",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-insurance-cash-value",
    name: "商业保险现金价值",
    category: "保险现金价值",
    amount: 110000,
    valuationMethod: "manual",
    currentValue: 110000,
    note: "储蓄型保险",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-reimbursement",
    name: "公司报销款",
    category: "应收款",
    amount: 15000,
    valuationMethod: "manual",
    currentValue: 15000,
    note: "待报销",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-friend-receivable",
    name: "朋友借款应收",
    category: "应收款",
    amount: 30000,
    valuationMethod: "manual",
    currentValue: 30000,
    note: "朋友待还",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "asset-side-project-equity",
    name: "个人副业项目权益",
    category: "项目权益",
    amount: 200000,
    valuationMethod: "manual",
    currentValue: 200000,
    note: "副业项目估值",
    createdAt: now,
    updatedAt: now,
  },
];

const liabilities: Liability[] = [
  {
    id: "liability-mortgage",
    name: "房贷剩余本金",
    category: "房贷",
    amount: 820000,
    dueDate: "2048-08-18",
    interestRate: 0.0385,
    note: "自住房贷款",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "liability-car-loan",
    name: "车贷",
    category: "车贷",
    amount: 90000,
    dueDate: "2029-05-20",
    interestRate: 0.041,
    note: "车辆贷款",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "liability-cmb-credit-card",
    name: "招商信用卡",
    category: "信用卡",
    amount: 38000,
    dueDate: "2026-05-25",
    accountId: "account-cmb-credit-card",
    note: "本期账单",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "liability-installment",
    name: "消费分期",
    category: "消费分期",
    amount: 26000,
    dueDate: "2026-12-31",
    note: "电子产品分期",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "liability-margin",
    name: "融资融券负债",
    category: "融资负债",
    amount: 150000,
    accountId: "account-margin",
    note: "证券账户融资",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "liability-tax-payable",
    name: "应付个税",
    category: "应付款",
    amount: 12000,
    dueDate: "2026-05-15",
    note: "待缴税款",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "liability-friend-borrowing",
    name: "朋友借款",
    category: "借款",
    amount: 50000,
    dueDate: "2026-08-31",
    note: "短期周转",
    createdAt: now,
    updatedAt: now,
  },
];

const april2026Transactions: Transaction[] = [
  {
    id: "tx-2026-04-salary",
    date: "2026-04-05",
    amount: 58000,
    type: "income",
    category: "工资薪金",
    accountId: "account-cmb-bank",
    cashFlowType: "operating",
    note: "工资到账58000",
    tags: ["主业", "稳定收入"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-consulting",
    date: "2026-04-08",
    amount: 18000,
    type: "income",
    category: "咨询收入",
    accountId: "account-wechat",
    cashFlowType: "operating",
    note: "咨询收入18000",
    tags: ["副业"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-side-project-dividend",
    date: "2026-04-10",
    amount: 12000,
    type: "income",
    category: "项目分红",
    accountId: "account-cmb-bank",
    cashFlowType: "operating",
    note: "副业项目分红12000",
    tags: ["副业", "分红"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-stock-dividend",
    date: "2026-04-15",
    amount: 3500,
    type: "income",
    category: "投资收益",
    accountId: "account-eastmoney",
    cashFlowType: "operating",
    note: "股息到账3500。V0.1 为匹配本期现金流口径，收入类现金流统一计入经营活动。",
    tags: ["投资收益"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-bond-fund-dividend",
    date: "2026-04-21",
    amount: 1200,
    type: "income",
    category: "投资收益",
    accountId: "account-cmb-bank",
    cashFlowType: "operating",
    note: "债基分红1200。V0.1 为匹配本期现金流口径，收入类现金流统一计入经营活动。",
    tags: ["投资收益"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-bank-interest",
    date: "2026-04-28",
    amount: 800,
    type: "income",
    category: "利息收入",
    accountId: "account-cmb-bank",
    cashFlowType: "operating",
    note: "银行利息800",
    tags: ["利息"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-mortgage-interest",
    date: "2026-04-01",
    amount: 3200,
    type: "expense",
    category: "居住",
    accountId: "account-cmb-bank",
    cashFlowType: "operating",
    note: "房贷月供利息部分",
    tags: ["房贷", "利息"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-mortgage-principal",
    date: "2026-04-01",
    amount: 5800,
    type: "liabilityDecrease",
    category: "房贷",
    accountId: "account-cmb-bank",
    relatedLiabilityId: "liability-mortgage",
    cashFlowType: "financing",
    note: "房贷本金偿还",
    tags: ["房贷", "还款"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-car-loan-interest",
    date: "2026-04-03",
    amount: 600,
    type: "expense",
    category: "车贷利息",
    accountId: "account-icbc-bank",
    cashFlowType: "operating",
    note: "车贷利息部分",
    tags: ["车贷", "利息"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-car-loan-principal",
    date: "2026-04-03",
    amount: 3400,
    type: "liabilityDecrease",
    category: "车贷",
    accountId: "account-icbc-bank",
    relatedLiabilityId: "liability-car-loan",
    cashFlowType: "financing",
    note: "车贷本金偿还",
    tags: ["车贷", "还款"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-food",
    date: "2026-04-06",
    amount: 6200,
    type: "expense",
    category: "餐饮",
    accountId: "account-wechat",
    cashFlowType: "operating",
    note: "餐饮支出",
    tags: ["日常消费"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-transport",
    date: "2026-04-07",
    amount: 2300,
    type: "expense",
    category: "交通",
    accountId: "account-alipay",
    cashFlowType: "operating",
    note: "交通出行",
    tags: ["通勤"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-property-utilities",
    date: "2026-04-09",
    amount: 2600,
    type: "expense",
    category: "居住",
    accountId: "account-alipay",
    cashFlowType: "operating",
    note: "物业水电",
    tags: ["居住"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-course",
    date: "2026-04-12",
    amount: 6800,
    type: "expense",
    category: "学习成长",
    accountId: "account-cmb-bank",
    cashFlowType: "operating",
    note: "高阶课程",
    tags: ["成长投入"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-insurance-payment",
    date: "2026-04-16",
    amount: 4500,
    type: "expense",
    category: "保险",
    accountId: "account-cmb-bank",
    cashFlowType: "operating",
    note: "商业保险缴费",
    tags: ["保障"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-family-support",
    date: "2026-04-18",
    amount: 8000,
    type: "expense",
    category: "家庭支持",
    accountId: "account-icbc-bank",
    cashFlowType: "operating",
    note: "家庭支持",
    tags: ["家庭"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-credit-card-travel",
    date: "2026-04-20",
    amount: 9000,
    type: "creditCardExpense",
    category: "旅行",
    accountId: "account-cmb-credit-card",
    relatedLiabilityId: "liability-cmb-credit-card",
    cashFlowType: "nonCash",
    note: "信用卡旅行消费9000。需求中同类旅行刷卡记录出现两次，此处保留一笔以匹配预期费用总额。",
    tags: ["信用卡", "旅行"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-entertainment",
    date: "2026-04-22",
    amount: 1800,
    type: "expense",
    category: "娱乐",
    accountId: "account-wechat",
    cashFlowType: "operating",
    note: "娱乐消费",
    tags: ["娱乐"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-communication",
    date: "2026-04-24",
    amount: 600,
    type: "expense",
    category: "通讯",
    accountId: "account-alipay",
    cashFlowType: "operating",
    note: "通讯支出",
    tags: ["通讯"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-buy-broad-etf",
    date: "2026-04-04",
    amount: 50000,
    type: "investmentBuy",
    category: "宽基ETF",
    accountId: "account-htsc-etf",
    relatedAssetId: "asset-broad-etf",
    cashFlowType: "investing",
    note: "买入宽基ETF50000",
    tags: ["投资", "ETF"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-buy-bond-fund",
    date: "2026-04-11",
    amount: 30000,
    type: "investmentBuy",
    category: "债券基金",
    accountId: "account-ttfund",
    relatedAssetId: "asset-bond-fund",
    cashFlowType: "investing",
    note: "买债券基金30000",
    tags: ["投资", "债券基金"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-buy-gold",
    date: "2026-04-19",
    amount: 10000,
    type: "investmentBuy",
    category: "黄金",
    accountId: "account-eastmoney",
    relatedAssetId: "asset-gold",
    cashFlowType: "investing",
    note: "买入黄金ETF10000",
    tags: ["投资", "黄金"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-sell-sector-etf",
    date: "2026-04-23",
    amount: 26000,
    type: "investmentSell",
    category: "行业ETF",
    accountId: "account-htsc-etf",
    relatedAssetId: "asset-sector-etf",
    cashFlowType: "investing",
    note: "卖出行业ETF到账26000。V0.1 暂不自动计算投资收益。",
    tags: ["投资", "卖出"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-fx-conversion",
    date: "2026-04-25",
    amount: 20000,
    type: "transfer",
    category: "外币资产",
    accountId: "account-cmb-bank",
    relatedAssetId: "asset-fx",
    cashFlowType: "nonCash",
    note: "美元换汇20000。V0.1 使用 transfer 作为内部资产转换测试，不计入收入、费用或现金流。",
    tags: ["资产调整", "外币"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-stock-unrealized-gain",
    date: "2026-04-27",
    amount: 35000,
    type: "assetIncrease",
    category: "A股股票",
    accountId: "account-eastmoney",
    relatedAssetId: "asset-a-share",
    cashFlowType: "nonCash",
    note: "股票账户浮盈35000。V0.1 不计入已实现利润，仅作为资产调整测试。",
    tags: ["资产调整", "浮盈"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-home-revaluation",
    date: "2026-04-29",
    amount: 20000,
    type: "assetIncrease",
    category: "房产",
    accountId: "account-cmb-bank",
    relatedAssetId: "asset-home",
    cashFlowType: "nonCash",
    note: "自住房估值调增20000。V0.1 不计入已实现利润，仅作为资产估值调整测试。",
    tags: ["资产调整", "房产"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-credit-card-repayment",
    date: "2026-04-17",
    amount: 30000,
    type: "creditCardRepayment",
    category: "信用卡",
    accountId: "account-cmb-bank",
    counterAccountId: "account-cmb-credit-card",
    relatedLiabilityId: "liability-cmb-credit-card",
    cashFlowType: "financing",
    note: "还信用卡30000",
    tags: ["还款", "信用卡"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-margin-repayment",
    date: "2026-04-26",
    amount: 20000,
    type: "liabilityDecrease",
    category: "融资负债",
    accountId: "account-eastmoney",
    relatedLiabilityId: "liability-margin",
    cashFlowType: "financing",
    note: "归还融资融券负债20000",
    tags: ["还款", "融资"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-friend-repayment",
    date: "2026-04-27",
    amount: 10000,
    type: "liabilityDecrease",
    category: "借款",
    accountId: "account-icbc-bank",
    relatedLiabilityId: "liability-friend-borrowing",
    cashFlowType: "financing",
    note: "归还朋友借款10000",
    tags: ["还款", "借款"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tx-2026-04-accrue-tax-payable",
    date: "2026-04-30",
    amount: 12000,
    type: "payableRecognize",
    category: "应付款",
    accountId: "account-cmb-bank",
    relatedLiabilityId: "liability-tax-payable",
    cashFlowType: "nonCash",
    note: "计提应付个税12000。V0.1 暂无计提类型，使用 liabilityIncrease 作为应付款确认测试。",
    tags: ["应付款", "个税"],
    createdAt: now,
    updatedAt: now,
  },
];

const transactions: Transaction[] = [...generateHistoricalTransactions(), ...april2026Transactions];

export const seedData: AppData = {
  version: APP_VERSION,
  accounts,
  assets,
  liabilities,
  transactions,
  journalEntries: [],
  settings: {
    currency: "CNY",
    defaultPeriod: "month",
    defaultReportMode: "simple",
    enableSampleData: true,
    createdAt: now,
    updatedAt: now,
  },
  currentPeriod: {
    id: "period-2026-04",
    type: "month",
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    label: "2026 年 4 月",
  },
};

export const createEmptyAppData = (): AppData => ({
  version: APP_VERSION,
  accounts: [],
  transactions: [],
  assets: [],
  liabilities: [],
  journalEntries: [],
  settings: {
    ...seedData.settings,
  },
  currentPeriod: {
    ...seedData.currentPeriod,
  },
});
