import type {
  Account,
  AppSettings,
  Asset,
  JournalEntry,
  Liability,
  ReportPeriod,
  Transaction,
} from "../domain/models";

export const APP_VERSION = "0.1.0";

const now = "2026-04-28T00:00:00.000Z";

export interface AppData {
  version: string;
  accounts: Account[];
  transactions: Transaction[];
  assets: Asset[];
  liabilities: Liability[];
  journalEntries: JournalEntry[];
  settings: AppSettings;
  currentPeriod: ReportPeriod;
}

export const seedData: AppData = {
  version: APP_VERSION,
  accounts: [
    {
      id: "account-bank-1",
      name: "招商银行卡",
      type: "bank",
      balance: 18650,
      currency: "CNY",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-wechat-1",
      name: "微信钱包",
      type: "wechat",
      balance: 860,
      currency: "CNY",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-alipay-1",
      name: "支付宝余额",
      type: "alipay",
      balance: 1230,
      currency: "CNY",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-cash-1",
      name: "现金",
      type: "cash",
      balance: 320,
      currency: "CNY",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-investment-1",
      name: "证券账户",
      type: "investment",
      balance: 42600,
      currency: "CNY",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-credit-card-1",
      name: "招商信用卡",
      type: "creditCard",
      balance: -3680,
      currency: "CNY",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-loan-1",
      name: "助学贷款",
      type: "loan",
      balance: -12000,
      currency: "CNY",
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  assets: [
    {
      id: "asset-bank-1",
      name: "招商银行卡余额",
      category: "bankDeposit",
      amount: 18650,
      valuationMethod: "currentValue",
      currentValue: 18650,
      accountId: "account-bank-1",
      note: "工资和日常备用金",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-wechat-1",
      name: "微信钱包余额",
      category: "paymentAccount",
      amount: 860,
      valuationMethod: "currentValue",
      currentValue: 860,
      accountId: "account-wechat-1",
      note: "日常小额支付",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-alipay-1",
      name: "支付宝余额",
      category: "paymentAccount",
      amount: 1230,
      valuationMethod: "currentValue",
      currentValue: 1230,
      accountId: "account-alipay-1",
      note: "生活支付账户",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-cash-1",
      name: "现金备用金",
      category: "cash",
      amount: 320,
      valuationMethod: "currentValue",
      currentValue: 320,
      accountId: "account-cash-1",
      note: "随身现金",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-fund-1",
      name: "指数基金持仓",
      category: "investment",
      amount: 28600,
      valuationMethod: "manual",
      currentValue: 28600,
      accountId: "account-investment-1",
      note: "长期投资资产",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-stock-1",
      name: "股票持仓",
      category: "investment",
      amount: 14000,
      valuationMethod: "manual",
      currentValue: 14000,
      accountId: "account-investment-1",
      note: "波动较高的权益资产",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-laptop-1",
      name: "笔记本电脑",
      category: "fixedAsset",
      amount: 8200,
      valuationMethod: "manual",
      purchaseDate: "2025-09-15",
      currentValue: 6200,
      note: "工作和学习设备，按当前估值记录",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-receivable-1",
      name: "朋友应还款",
      category: "receivable",
      amount: 1500,
      valuationMethod: "manual",
      currentValue: 1500,
      note: "短期应收款示例",
      createdAt: now,
      updatedAt: now,
    },
  ],
  liabilities: [
    {
      id: "liability-credit-card-1",
      name: "招商信用卡应还款",
      category: "creditCard",
      amount: 3680,
      dueDate: "2026-05-10",
      accountId: "account-credit-card-1",
      note: "本月账单待还",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-huabei-1",
      name: "花呗待还",
      category: "huabei",
      amount: 760,
      dueDate: "2026-05-09",
      note: "生活消费分期示例",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-loan-1",
      name: "助学贷款余额",
      category: "loan",
      amount: 12000,
      dueDate: "2026-12-20",
      interestRate: 0.032,
      accountId: "account-loan-1",
      note: "长期负债示例",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-borrowing-1",
      name: "向家人借款",
      category: "borrowing",
      amount: 3000,
      dueDate: "2026-06-30",
      note: "短期周转借款",
      createdAt: now,
      updatedAt: now,
    },
  ],
  transactions: [
    {
      id: "tx-income-1",
      date: "2026-04-03",
      amount: 9200,
      type: "income",
      category: "工资薪金",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "4 月工资到账",
      tags: ["主业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-income-2",
      date: "2026-04-08",
      amount: 1800,
      type: "income",
      category: "副业收入",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "周末剪辑项目结算",
      tags: ["副业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-income-3",
      date: "2026-03-25",
      amount: 320,
      type: "income",
      category: "投资收益",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "基金分红到账",
      tags: ["投资收益"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-food-1",
      date: "2026-04-05",
      amount: 58,
      type: "expense",
      category: "餐饮",
      accountId: "account-wechat-1",
      cashFlowType: "operating",
      note: "午饭和咖啡",
      tags: ["日常消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-rent-1",
      date: "2026-04-06",
      amount: 2600,
      type: "expense",
      category: "居住",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "房租",
      tags: ["必要成本"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-transport-1",
      date: "2026-04-09",
      amount: 126,
      type: "expense",
      category: "交通",
      accountId: "account-alipay-1",
      cashFlowType: "operating",
      note: "地铁、打车和共享单车",
      tags: ["通勤"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-study-1",
      date: "2026-04-12",
      amount: 699,
      type: "expense",
      category: "学习成长",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "数据分析课程",
      tags: ["成长投入"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-health-1",
      date: "2026-04-16",
      amount: 236,
      type: "expense",
      category: "医疗健康",
      accountId: "account-alipay-1",
      cashFlowType: "operating",
      note: "体检复查和药品",
      tags: ["健康"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-entertainment-1",
      date: "2026-04-20",
      amount: 168,
      type: "expense",
      category: "娱乐",
      accountId: "account-wechat-1",
      cashFlowType: "operating",
      note: "电影和饮品",
      tags: ["生活消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-investment-buy-1",
      date: "2026-04-10",
      amount: 3000,
      type: "investmentBuy",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-fund-1",
      cashFlowType: "investing",
      note: "定投指数基金，不直接影响利润",
      tags: ["投资"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-investment-buy-2",
      date: "2026-03-18",
      amount: 2500,
      type: "investmentBuy",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-stock-1",
      cashFlowType: "investing",
      note: "买入股票",
      tags: ["投资"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-investment-sell-1",
      date: "2026-04-22",
      amount: 1500,
      type: "investmentSell",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-fund-1",
      cashFlowType: "investing",
      note: "赎回部分基金，V0.1 暂不自动计算投资收益",
      tags: ["投资"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-credit-card-expense-1",
      date: "2026-04-13",
      amount: 428,
      type: "creditCardExpense",
      category: "餐饮",
      accountId: "account-credit-card-1",
      relatedLiabilityId: "liability-credit-card-1",
      cashFlowType: "nonCash",
      note: "信用卡请客吃饭，不产生现金流",
      tags: ["信用卡"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-credit-card-expense-2",
      date: "2026-04-15",
      amount: 899,
      type: "creditCardExpense",
      category: "数码设备",
      accountId: "account-credit-card-1",
      relatedLiabilityId: "liability-credit-card-1",
      cashFlowType: "nonCash",
      note: "信用卡购买降噪耳机",
      tags: ["信用卡", "消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-credit-card-repayment-1",
      date: "2026-04-18",
      amount: 1200,
      type: "creditCardRepayment",
      category: "信用卡还款",
      accountId: "account-bank-1",
      relatedLiabilityId: "liability-credit-card-1",
      cashFlowType: "financing",
      note: "偿还部分信用卡账单",
      tags: ["还款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-liability-increase-1",
      date: "2026-03-28",
      amount: 3000,
      type: "liabilityIncrease",
      category: "临时借款",
      accountId: "account-bank-1",
      relatedLiabilityId: "liability-borrowing-1",
      cashFlowType: "financing",
      note: "向家人借入周转资金",
      tags: ["筹资"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-liability-decrease-1",
      date: "2026-04-24",
      amount: 800,
      type: "liabilityDecrease",
      category: "借款还款",
      accountId: "account-bank-1",
      relatedLiabilityId: "liability-borrowing-1",
      cashFlowType: "financing",
      note: "归还家人借款",
      tags: ["还款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-receivable-collection-1",
      date: "2026-04-26",
      amount: 500,
      type: "assetDecrease",
      category: "应收款调整",
      accountId: "account-bank-1",
      relatedAssetId: "asset-receivable-1",
      cashFlowType: "nonCash",
      note: "应收款手动调减，V0.1 暂不同时生成现金流入",
      tags: ["应收款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-asset-increase-1",
      date: "2026-02-14",
      amount: 1200,
      type: "assetIncrease",
      category: "礼物资产",
      accountId: "account-cash-1",
      cashFlowType: "nonCash",
      note: "收到家人红包，作为资产增加示例",
      tags: ["资产变动"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-march-1",
      date: "2026-03-08",
      amount: 430,
      type: "expense",
      category: "服饰",
      accountId: "account-alipay-1",
      cashFlowType: "operating",
      note: "换季衣物",
      tags: ["生活消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-income-feb-1",
      date: "2026-02-05",
      amount: 8800,
      type: "income",
      category: "工资薪金",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "2 月工资",
      tags: ["主业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-expense-feb-1",
      date: "2026-02-21",
      amount: 980,
      type: "expense",
      category: "旅行",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "周末短途旅行",
      tags: ["体验消费"],
      createdAt: now,
      updatedAt: now,
    },
  ],
  journalEntries: [
    {
      id: "journal-income-1",
      transactionId: "tx-income-1",
      date: "2026-04-03",
      description: "4 月工资到账",
      lines: [
        {
          accountCode: "1002",
          accountName: "银行存款",
          debit: 9200,
          credit: 0,
          reportElement: "asset",
        },
        {
          accountCode: "6001",
          accountName: "工资薪金收入",
          debit: 0,
          credit: 9200,
          reportElement: "income",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "journal-expense-rent-1",
      transactionId: "tx-expense-rent-1",
      date: "2026-04-06",
      description: "支付房租",
      lines: [
        {
          accountCode: "6602",
          accountName: "居住费用",
          debit: 2600,
          credit: 0,
          reportElement: "expense",
        },
        {
          accountCode: "1002",
          accountName: "银行存款",
          debit: 0,
          credit: 2600,
          reportElement: "asset",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
  settings: {
    currency: "CNY",
    defaultPeriod: "month",
    defaultReportMode: "simple",
    enableSampleData: true,
    createdAt: now,
    updatedAt: now,
  },
  currentPeriod: {
    id: "period-2026-04",
    type: "month",
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    label: "2026 年 4 月",
  },
};

export const createEmptyAppData = (): AppData => ({
  version: APP_VERSION,
  accounts: [],
  transactions: [],
  assets: [],
  liabilities: [],
  journalEntries: [],
  settings: {
    ...seedData.settings,
  },
  currentPeriod: {
    ...seedData.currentPeriod,
  },
});
