import type {
  Account,
  AppSettings,
  Asset,
  JournalEntry,
  Liability,
  ReportPeriod,
  Transaction,
} from "../domain/models";

export const APP_VERSION = "0.1.0";

const now = "2026-04-28T00:00:00.000Z";

export interface AppData {
  version: string;
  accounts: Account[];
  transactions: Transaction[];
  assets: Asset[];
  liabilities: Liability[];
  journalEntries: JournalEntry[];
  settings: AppSettings;
  currentPeriod: ReportPeriod;
}

export const seedData: AppData = {
  version: APP_VERSION,
  accounts: [
    {
      id: "account-bank-1",
      name: "招商银行卡",
      type: "bank",
      balance: 120000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "工资卡和主要现金池",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-bank-2",
      name: "工商银行卡",
      type: "bank",
      balance: 85000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "房贷、保险和大额支出账户",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-bank-3",
      name: "建设银行卡",
      type: "bank",
      balance: 38000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "备用金和家庭支援账户",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-wechat-1",
      name: "微信零钱",
      type: "wechat",
      balance: 6800,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "日常小额支付",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-alipay-1",
      name: "支付宝余额",
      type: "alipay",
      balance: 12500,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "生活消费和花呗还款",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-securities-1",
      name: "东方财富证券",
      type: "securities",
      balance: 260000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "A 股股票持仓",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-securities-2",
      name: "华泰证券",
      type: "securities",
      balance: 180000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "ETF 和可转债持仓",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-fund-1",
      name: "天天基金账户",
      type: "fund",
      balance: 320000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "长期指数基金定投",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-fund-2",
      name: "蚂蚁基金账户",
      type: "fund",
      balance: 95000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "债券基金和货币基金",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-credit-card-1",
      name: "招商信用卡",
      type: "creditCard",
      balance: -18500,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "日常刷卡和差旅垫付",
      creditLimit: 80000,
      currentDebt: 18500,
      billDay: 20,
      repaymentDay: 10,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-credit-card-2",
      name: "中信信用卡",
      type: "creditCard",
      balance: -6200,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "订阅、数码设备和境外消费",
      creditLimit: 50000,
      currentDebt: 6200,
      billDay: 16,
      repaymentDay: 6,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-credit-card-3",
      name: "广发信用卡",
      type: "creditCard",
      balance: 0,
      currency: "CNY",
      isEnabled: false,
      isActive: false,
      note: "旧卡，已停用，保留历史记录",
      creditLimit: 30000,
      currentDebt: 0,
      billDay: 12,
      repaymentDay: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-other-1",
      name: "备用现金",
      type: "other",
      balance: 5000,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "家中应急现金",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "account-other-2",
      name: "数字人民币钱包",
      type: "other",
      balance: 2600,
      currency: "CNY",
      isEnabled: true,
      isActive: true,
      note: "小额试点钱包",
      createdAt: now,
      updatedAt: now,
    },
  ],
  assets: [
    {
      id: "asset-bank-1",
      name: "招商银行卡余额",
      category: "bankDeposit",
      amount: 120000,
      valuationMethod: "currentValue",
      currentValue: 120000,
      accountId: "account-bank-1",
      note: "工资、奖金和日常现金池",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-bank-2",
      name: "工商银行卡余额",
      category: "bankDeposit",
      amount: 85000,
      valuationMethod: "currentValue",
      currentValue: 85000,
      accountId: "account-bank-2",
      note: "大额支出备用金",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-bank-3",
      name: "建设银行卡余额",
      category: "bankDeposit",
      amount: 38000,
      valuationMethod: "currentValue",
      currentValue: 38000,
      accountId: "account-bank-3",
      note: "家庭支援和应急金",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-wechat-1",
      name: "微信零钱",
      category: "paymentAccount",
      amount: 6800,
      valuationMethod: "currentValue",
      currentValue: 6800,
      accountId: "account-wechat-1",
      note: "日常小额支付",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-alipay-1",
      name: "支付宝余额",
      category: "paymentAccount",
      amount: 12500,
      valuationMethod: "currentValue",
      currentValue: 12500,
      accountId: "account-alipay-1",
      note: "生活支付和花呗还款",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-cash-1",
      name: "备用现金",
      category: "cash",
      amount: 5000,
      valuationMethod: "currentValue",
      currentValue: 5000,
      accountId: "account-other-1",
      note: "家中应急现金",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-digital-cny-1",
      name: "数字人民币钱包",
      category: "cash",
      amount: 2600,
      valuationMethod: "currentValue",
      currentValue: 2600,
      accountId: "account-other-2",
      note: "小额试点钱包",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-stock-a-1",
      name: "A 股股票组合",
      category: "investment",
      amount: 260000,
      valuationMethod: "manual",
      currentValue: 260000,
      accountId: "account-securities-1",
      note: "消费、科技和高股息股票组合",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-etf-1",
      name: "ETF 与可转债组合",
      category: "investment",
      amount: 180000,
      valuationMethod: "manual",
      currentValue: 180000,
      accountId: "account-securities-2",
      note: "宽基 ETF、红利 ETF、可转债",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-index-fund-1",
      name: "指数基金组合",
      category: "investment",
      amount: 320000,
      valuationMethod: "manual",
      currentValue: 320000,
      accountId: "account-fund-1",
      note: "长期指数基金定投",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-bond-fund-1",
      name: "债券基金与货币基金",
      category: "investment",
      amount: 95000,
      valuationMethod: "manual",
      currentValue: 95000,
      accountId: "account-fund-2",
      note: "低波动资金池",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-gold-1",
      name: "黄金 ETF",
      category: "investment",
      amount: 82000,
      valuationMethod: "manual",
      currentValue: 82000,
      note: "抗通胀资产",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-apartment-1",
      name: "自住房当前估值",
      category: "fixedAsset",
      amount: 1850000,
      valuationMethod: "manual",
      purchaseDate: "2023-08-18",
      currentValue: 1850000,
      note: "自住固定资产，按当前估值记录",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-car-1",
      name: "新能源车当前估值",
      category: "fixedAsset",
      amount: 168000,
      valuationMethod: "manual",
      purchaseDate: "2025-05-20",
      currentValue: 168000,
      note: "通勤车辆，按当前二手估值记录",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-equipment-1",
      name: "电脑相机与生产设备",
      category: "fixedAsset",
      amount: 42000,
      valuationMethod: "manual",
      purchaseDate: "2025-09-15",
      currentValue: 42000,
      note: "工作和内容生产设备",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-receivable-client-1",
      name: "客户项目尾款",
      category: "receivable",
      amount: 28000,
      valuationMethod: "manual",
      currentValue: 28000,
      note: "副业项目已交付，等待结算",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "asset-receivable-friend-1",
      name: "朋友短期借款应收",
      category: "receivable",
      amount: 12000,
      valuationMethod: "manual",
      currentValue: 12000,
      note: "预计 5 月归还",
      createdAt: now,
      updatedAt: now,
    },
  ],
  liabilities: [
    {
      id: "liability-credit-card-1",
      name: "招商信用卡应还款",
      category: "creditCard",
      amount: 18500,
      dueDate: "2026-05-10",
      accountId: "account-credit-card-1",
      note: "差旅、餐饮和大额刷卡待还",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-credit-card-2",
      name: "中信信用卡应还款",
      category: "creditCard",
      amount: 6200,
      dueDate: "2026-05-06",
      accountId: "account-credit-card-2",
      note: "订阅、软件和境外消费",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-huabei-1",
      name: "花呗待还",
      category: "huabei",
      amount: 5800,
      dueDate: "2026-05-09",
      note: "生活消费分期",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-jd-1",
      name: "白条待还",
      category: "huabei",
      amount: 3200,
      dueDate: "2026-05-12",
      note: "家电分期尾款",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-mortgage-1",
      name: "住房贷款余额",
      category: "loan",
      amount: 980000,
      dueDate: "2048-08-18",
      interestRate: 0.0385,
      note: "自住房按揭贷款",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-car-loan-1",
      name: "车贷余额",
      category: "loan",
      amount: 82000,
      dueDate: "2029-05-20",
      interestRate: 0.041,
      note: "新能源车贷款",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-education-loan-1",
      name: "助学贷款余额",
      category: "loan",
      amount: 32000,
      dueDate: "2030-12-20",
      interestRate: 0.032,
      note: "长期教育贷款",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-family-borrowing-1",
      name: "向家人借款",
      category: "borrowing",
      amount: 50000,
      dueDate: "2026-12-31",
      note: "买房装修临时周转",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "liability-payable-rent-1",
      name: "待付物业和取暖费",
      category: "payable",
      amount: 6400,
      dueDate: "2026-05-15",
      note: "年度物业费和取暖费",
      createdAt: now,
      updatedAt: now,
    },
  ],
  transactions: [
    {
      id: "tx-2026-04-salary",
      date: "2026-04-03",
      amount: 45000,
      type: "income",
      category: "工资薪金",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "4 月工资到账",
      tags: ["主业", "稳定收入"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-bonus",
      date: "2026-04-05",
      amount: 90000,
      type: "income",
      category: "季度奖金",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "一季度绩效奖金",
      tags: ["主业", "奖金"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-consulting",
      date: "2026-04-08",
      amount: 22000,
      type: "income",
      category: "副业收入",
      accountId: "account-bank-3",
      cashFlowType: "operating",
      note: "企业咨询项目首款",
      tags: ["副业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-content",
      date: "2026-04-12",
      amount: 6500,
      type: "income",
      category: "内容平台收入",
      accountId: "account-alipay-1",
      cashFlowType: "operating",
      note: "自媒体平台结算",
      tags: ["副业", "自媒体"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-dividend",
      date: "2026-04-18",
      amount: 3800,
      type: "income",
      category: "投资收益",
      accountId: "account-bank-2",
      cashFlowType: "operating",
      note: "红利和基金分红到账",
      tags: ["投资收益"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-rent",
      date: "2026-04-02",
      amount: 7200,
      type: "expense",
      category: "居住",
      accountId: "account-bank-2",
      cashFlowType: "operating",
      note: "短租房和停车位支出",
      tags: ["必要成本"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-food",
      date: "2026-04-06",
      amount: 2860,
      type: "expense",
      category: "餐饮",
      accountId: "account-wechat-1",
      cashFlowType: "operating",
      note: "本月外卖、聚餐和咖啡",
      tags: ["日常消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-transport",
      date: "2026-04-09",
      amount: 1680,
      type: "expense",
      category: "交通",
      accountId: "account-alipay-1",
      cashFlowType: "operating",
      note: "打车、地铁、高铁和停车费",
      tags: ["通勤"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-study",
      date: "2026-04-11",
      amount: 9800,
      type: "expense",
      category: "学习成长",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "财务建模和产品课程",
      tags: ["成长投入"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-health",
      date: "2026-04-14",
      amount: 5200,
      type: "expense",
      category: "医疗健康",
      accountId: "account-bank-2",
      cashFlowType: "operating",
      note: "体检、牙科和药品",
      tags: ["健康"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-family",
      date: "2026-04-16",
      amount: 12000,
      type: "expense",
      category: "家庭支持",
      accountId: "account-bank-3",
      cashFlowType: "operating",
      note: "给父母生活费和家庭支援",
      tags: ["家庭"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-insurance",
      date: "2026-04-19",
      amount: 18500,
      type: "expense",
      category: "保险",
      accountId: "account-bank-2",
      cashFlowType: "operating",
      note: "重疾险、医疗险和车险年度缴费",
      tags: ["保障"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-travel",
      date: "2026-04-21",
      amount: 13600,
      type: "creditCardExpense",
      category: "旅行",
      accountId: "account-credit-card-1",
      relatedLiabilityId: "liability-credit-card-1",
      cashFlowType: "nonCash",
      note: "信用卡支付假期机票和酒店",
      tags: ["信用卡", "体验消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-device",
      date: "2026-04-23",
      amount: 16800,
      type: "creditCardExpense",
      category: "数码设备",
      accountId: "account-credit-card-2",
      relatedLiabilityId: "liability-credit-card-2",
      cashFlowType: "nonCash",
      note: "信用卡购买工作手机和显示器",
      tags: ["信用卡", "生产设备"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-credit-card-repayment-1",
      date: "2026-04-25",
      amount: 15000,
      type: "creditCardRepayment",
      category: "信用卡还款",
      accountId: "account-bank-1",
      relatedLiabilityId: "liability-credit-card-1",
      cashFlowType: "financing",
      note: "偿还招商信用卡部分账单",
      tags: ["还款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-investment-buy-fund",
      date: "2026-04-10",
      amount: 50000,
      type: "investmentBuy",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-index-fund-1",
      cashFlowType: "investing",
      note: "加仓指数基金",
      tags: ["投资", "基金"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-investment-buy-stock",
      date: "2026-04-17",
      amount: 80000,
      type: "investmentBuy",
      category: "投资资产",
      accountId: "account-bank-2",
      relatedAssetId: "asset-stock-a-1",
      cashFlowType: "investing",
      note: "买入高股息股票组合",
      tags: ["投资", "股票"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-investment-sell-etf",
      date: "2026-04-26",
      amount: 45000,
      type: "investmentSell",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-etf-1",
      cashFlowType: "investing",
      note: "卖出部分 ETF，V0.1 暂不自动计算投资收益",
      tags: ["投资", "卖出"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-mortgage",
      date: "2026-04-20",
      amount: 9800,
      type: "liabilityDecrease",
      category: "房贷还款",
      accountId: "account-bank-2",
      relatedLiabilityId: "liability-mortgage-1",
      cashFlowType: "financing",
      note: "住房贷款月供",
      tags: ["房贷", "还款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-family-borrowing",
      date: "2026-04-03",
      amount: 50000,
      type: "liabilityIncrease",
      category: "家庭借款",
      accountId: "account-bank-3",
      relatedLiabilityId: "liability-family-borrowing-1",
      cashFlowType: "financing",
      note: "装修临时周转借入",
      tags: ["筹资"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-04-receivable-collection",
      date: "2026-04-28",
      amount: 15000,
      type: "assetDecrease",
      category: "应收款回收",
      accountId: "account-bank-1",
      relatedAssetId: "asset-receivable-client-1",
      cashFlowType: "nonCash",
      note: "客户尾款部分收回，V0.1 暂不同时生成现金流入",
      tags: ["应收款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-03-salary",
      date: "2026-03-03",
      amount: 45000,
      type: "income",
      category: "工资薪金",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "3 月工资到账",
      tags: ["主业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-03-side-project",
      date: "2026-03-12",
      amount: 18000,
      type: "income",
      category: "副业收入",
      accountId: "account-bank-3",
      cashFlowType: "operating",
      note: "数据看板项目结算",
      tags: ["副业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-03-rent",
      date: "2026-03-04",
      amount: 7200,
      type: "expense",
      category: "居住",
      accountId: "account-bank-2",
      cashFlowType: "operating",
      note: "3 月房租和停车费",
      tags: ["必要成本"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-03-food",
      date: "2026-03-10",
      amount: 2460,
      type: "expense",
      category: "餐饮",
      accountId: "account-wechat-1",
      cashFlowType: "operating",
      note: "3 月餐饮汇总",
      tags: ["日常消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-03-travel",
      date: "2026-03-18",
      amount: 9200,
      type: "expense",
      category: "旅行",
      accountId: "account-credit-card-1",
      cashFlowType: "nonCash",
      note: "周末短途旅行刷卡",
      tags: ["信用卡", "体验消费"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-03-investment-buy",
      date: "2026-03-16",
      amount: 60000,
      type: "investmentBuy",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-etf-1",
      cashFlowType: "investing",
      note: "买入红利 ETF 和债券基金",
      tags: ["投资"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-03-car-loan",
      date: "2026-03-21",
      amount: 4200,
      type: "liabilityDecrease",
      category: "车贷还款",
      accountId: "account-bank-2",
      relatedLiabilityId: "liability-car-loan-1",
      cashFlowType: "financing",
      note: "车贷月供",
      tags: ["还款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-02-salary",
      date: "2026-02-03",
      amount: 45000,
      type: "income",
      category: "工资薪金",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "2 月工资到账",
      tags: ["主业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-02-year-end",
      date: "2026-02-08",
      amount: 120000,
      type: "income",
      category: "年终奖",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "年终奖金到账",
      tags: ["奖金"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-02-new-year",
      date: "2026-02-10",
      amount: 22000,
      type: "expense",
      category: "节日支出",
      accountId: "account-bank-3",
      cashFlowType: "operating",
      note: "春节红包、礼物和家庭聚餐",
      tags: ["家庭", "节日"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-02-health",
      date: "2026-02-16",
      amount: 3800,
      type: "expense",
      category: "医疗健康",
      accountId: "account-alipay-1",
      cashFlowType: "operating",
      note: "体检套餐和运动康复",
      tags: ["健康"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-02-investment-buy",
      date: "2026-02-19",
      amount: 100000,
      type: "investmentBuy",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-index-fund-1",
      cashFlowType: "investing",
      note: "年终奖部分投入长期指数基金",
      tags: ["投资", "基金"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-02-credit-card-repayment",
      date: "2026-02-25",
      amount: 18000,
      type: "creditCardRepayment",
      category: "信用卡还款",
      accountId: "account-bank-1",
      relatedLiabilityId: "liability-credit-card-1",
      cashFlowType: "financing",
      note: "偿还春节刷卡账单",
      tags: ["还款"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-01-salary",
      date: "2026-01-03",
      amount: 45000,
      type: "income",
      category: "工资薪金",
      accountId: "account-bank-1",
      cashFlowType: "operating",
      note: "1 月工资到账",
      tags: ["主业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-01-consulting",
      date: "2026-01-18",
      amount: 30000,
      type: "income",
      category: "副业收入",
      accountId: "account-bank-3",
      cashFlowType: "operating",
      note: "年度顾问费首期",
      tags: ["副业"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-01-home-renovation",
      date: "2026-01-12",
      amount: 36000,
      type: "expense",
      category: "居住改善",
      accountId: "account-bank-2",
      cashFlowType: "operating",
      note: "软装、家电和维修",
      tags: ["居住", "改善"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-01-credit-card-expense",
      date: "2026-01-20",
      amount: 7800,
      type: "creditCardExpense",
      category: "订阅与软件",
      accountId: "account-credit-card-2",
      relatedLiabilityId: "liability-credit-card-2",
      cashFlowType: "nonCash",
      note: "年度软件订阅和云服务",
      tags: ["信用卡", "工具"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-01-investment-sell",
      date: "2026-01-26",
      amount: 40000,
      type: "investmentSell",
      category: "投资资产",
      accountId: "account-bank-1",
      relatedAssetId: "asset-bond-fund-1",
      cashFlowType: "investing",
      note: "赎回部分债券基金补充现金",
      tags: ["投资", "卖出"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx-2026-01-mortgage",
      date: "2026-01-20",
      amount: 9800,
      type: "liabilityDecrease",
      category: "房贷还款",
      accountId: "account-bank-2",
      relatedLiabilityId: "liability-mortgage-1",
      cashFlowType: "financing",
      note: "住房贷款月供",
      tags: ["房贷"],
      createdAt: now,
      updatedAt: now,
    },
  ],
  journalEntries: [
    {
      id: "journal-income-2026-04-salary",
      transactionId: "tx-2026-04-salary",
      date: "2026-04-03",
      description: "4 月工资到账",
      lines: [
        {
          accountCode: "1002",
          accountName: "银行存款",
          debit: 45000,
          credit: 0,
          reportElement: "asset",
        },
        {
          accountCode: "6001",
          accountName: "工资薪金收入",
          debit: 0,
          credit: 45000,
          reportElement: "income",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "journal-bonus-2026-04",
      transactionId: "tx-2026-04-bonus",
      date: "2026-04-05",
      description: "一季度绩效奖金到账",
      lines: [
        {
          accountCode: "1002",
          accountName: "银行存款",
          debit: 90000,
          credit: 0,
          reportElement: "asset",
        },
        {
          accountCode: "6001",
          accountName: "奖金收入",
          debit: 0,
          credit: 90000,
          reportElement: "income",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "journal-expense-2026-04-study",
      transactionId: "tx-2026-04-study",
      date: "2026-04-11",
      description: "支付财务建模和产品课程",
      lines: [
        {
          accountCode: "6602",
          accountName: "学习成长费用",
          debit: 9800,
          credit: 0,
          reportElement: "expense",
        },
        {
          accountCode: "1002",
          accountName: "银行存款",
          debit: 0,
          credit: 9800,
          reportElement: "asset",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "journal-credit-card-2026-04-device",
      transactionId: "tx-2026-04-device",
      date: "2026-04-23",
      description: "信用卡购买工作设备",
      lines: [
        {
          accountCode: "6602",
          accountName: "数码设备费用",
          debit: 16800,
          credit: 0,
          reportElement: "expense",
        },
        {
          accountCode: "2202",
          accountName: "信用卡负债",
          debit: 0,
          credit: 16800,
          reportElement: "liability",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
  settings: {
    currency: "CNY",
    defaultPeriod: "month",
    defaultReportMode: "simple",
    enableSampleData: true,
    createdAt: now,
    updatedAt: now,
  },
  currentPeriod: {
    id: "period-2026-04",
    type: "month",
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    label: "2026 年 4 月",
  },
};

export const createEmptyAppData = (): AppData => ({
  version: APP_VERSION,
  accounts: [],
  transactions: [],
  assets: [],
  liabilities: [],
  journalEntries: [],
  settings: {
    ...seedData.settings,
  },
  currentPeriod: {
    ...seedData.currentPeriod,
  },
});
